
CREATE TABLE CLIENTES(
CIF VARCHAR(9) PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL,
DIRECCION VARCHAR(50) NOT NULL,
CP VARCHAR(50) NOT NULL,
CIUDAD VARCHAR(50) NOT NULL,
PROVINCIA VARCHAR(50) NOT NULL,
TELEFONO VARCHAR(9) NOT NULL,
EMAIL VARCHAR(70) NOT NULL,
SALDO DECIMAL(20,2) NOT NULL DEFAULT 0,
OBSERVACIONES VARCHAR(200)
);